name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [release, debug]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            generator: "Visual Studio 17 2022"
            vcpkg_triplet: x64-windows
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            generator: "Unix Makefiles"
            vcpkg_triplet: x64-linux

    steps:
    - uses: actions/checkout@v4

    # Setup vcpkg
    - name: vcpkg build
      id: vcpkg
      uses: johnwason/vcpkg-action@v7
      with:
        manifest-dir: ${{ github.workspace }}/../../ # Set to directory containing vcpkg.json
        triplet: ${{ matrix.include.vcpkg_triplet }}
        cache-key: ${{ matrix.config.os }}
        token: ${{ github.token }}


    # Install dependencies
    - name: Install dependencies
      run: |
        vcpkg install drogon --triplet ${{ matrix.vcpkg_triplet }}
        vcpkg integrate install

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    # Configure CMake with secret environment variables
    - name: Configure CMake
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWD: ${{ secrets.DB_PASSWD }}
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
          -G "${{ matrix.generator }}" \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake \
          -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }} --output-on-failure
